"""P2-01 service contract layer: versioned schema, receipt semantics, identity/authorization.

This package is the contract the P2 write path will be built against
(``docs/design/p2-write-path-minimal-loop.md`` §7.4).  It contains no server, no socket, no
database file and no CLI entry point, and ``memory_tool`` does not import it: importing the
package has no effect on the running tool.  The negative tests in
``tests/unit/test_service_contract_negative.py`` (N1-N11) were written before this code.

Layering:

* :mod:`memory_tool.service_contract.versioning` - contract version, wire schemas, validation.
* :mod:`memory_tool.service_contract.identity` - principals, grants, effective scope.
* :mod:`memory_tool.service_contract.models` - transport-agnostic request/result shapes.
* :mod:`memory_tool.service_contract.receipts` - receipt and client outbox semantics.
* :mod:`memory_tool.service_contract.storage` - the declared (unexecuted) service schema.
* :mod:`memory_tool.service_contract.adapter` - the in-process reference adapter.
"""
from __future__ import annotations

from .adapter import (
    CHANGELOG_OK,
    PROJECTION_INVALIDATION_SECONDS,
    RESNAPSHOT_REQUIRED,
    InProcessAdapter,
)
from .errors import (
    ContractError,
    ErasedRecordNotReadable,
    EvidenceRequiredForAssertion,
    FaceNotGranted,
    IdempotencyConflict,
    IdentityFieldRejected,
    MissingContractVersion,
    OfflineWriteNotAccepted,
    RecordNotFound,
    RetractedRecordNotReadable,
    RevisionConflict,
    ScopeNotGranted,
    Unauthenticated,
    UnsupportedContractVersion,
    UnsupportedSchemaKeyword,
    WireSchemaViolation,
)
from .identity import (
    FACE_ACTION,
    IDENTITY_FIELDS,
    SERVER_FIELDS,
    Action,
    Credential,
    EffectiveScope,
    Face,
    Grant,
    Principal,
    Registration,
    RequestedScope,
    Visibility,
    compute_effective_scope,
    hash_secret,
    reject_server_owned_fields,
    verify_secret,
)
from .models import (
    ERASURE_TARGETS,
    UNASSIGNED,
    AliasConflict,
    ChangelogDelta,
    ClaimStatus,
    ConflictRecord,
    CursorReadResult,
    Degradation,
    ErasureManifest,
    ErasureReplay,
    EventSubmission,
    EventView,
    EvidenceLink,
    FaceItem,
    FaceRequest,
    FaceResult,
    Lifecycle,
    MemoryProposal,
    ProjectRegistry,
    Tombstone,
    parse_claim_status,
    payload_hash,
)
from .receipts import (
    ClientOutbox,
    ClientOutboxItem,
    OutboxState,
    Receipt,
    ReceiptState,
    Stages,
    make_queued_receipt,
)
from .storage import (
    SERVICE_DB_FILENAME,
    STORAGE_DDL,
    STORAGE_PRAGMAS,
    STORAGE_SCHEMA_ADDITIONS,
    STORAGE_SCHEMA_VERSION,
    declared_columns,
    declared_tables,
)
from .versioning import (
    CONTRACT_VERSION,
    SUPPORTED_SCHEMA_KEYWORDS,
    WIRE_SCHEMA_VERSION,
    assert_supported_keywords,
    check_contract_version,
    load_wire_schema,
    parse_version,
    validate_wire,
    wire_schema_names,
)

__all__ = [
    "CHANGELOG_OK",
    "CONTRACT_VERSION",
    "ERASURE_TARGETS",
    "FACE_ACTION",
    "IDENTITY_FIELDS",
    "PROJECTION_INVALIDATION_SECONDS",
    "RESNAPSHOT_REQUIRED",
    "SERVICE_DB_FILENAME",
    "SERVER_FIELDS",
    "STORAGE_DDL",
    "STORAGE_PRAGMAS",
    "STORAGE_SCHEMA_ADDITIONS",
    "STORAGE_SCHEMA_VERSION",
    "SUPPORTED_SCHEMA_KEYWORDS",
    "UNASSIGNED",
    "WIRE_SCHEMA_VERSION",
    "Action",
    "AliasConflict",
    "ChangelogDelta",
    "ClaimStatus",
    "ClientOutbox",
    "ClientOutboxItem",
    "ConflictRecord",
    "ContractError",
    "Credential",
    "CursorReadResult",
    "Degradation",
    "EffectiveScope",
    "ErasureManifest",
    "ErasureReplay",
    "ErasedRecordNotReadable",
    "EventSubmission",
    "EventView",
    "EvidenceLink",
    "EvidenceRequiredForAssertion",
    "Face",
    "FaceItem",
    "FaceNotGranted",
    "FaceRequest",
    "FaceResult",
    "Grant",
    "IdempotencyConflict",
    "IdentityFieldRejected",
    "InProcessAdapter",
    "Lifecycle",
    "MemoryProposal",
    "MissingContractVersion",
    "OfflineWriteNotAccepted",
    "OutboxState",
    "Principal",
    "ProjectRegistry",
    "Receipt",
    "ReceiptState",
    "RecordNotFound",
    "Registration",
    "RequestedScope",
    "RetractedRecordNotReadable",
    "RevisionConflict",
    "ScopeNotGranted",
    "Stages",
    "Tombstone",
    "Unauthenticated",
    "UnsupportedContractVersion",
    "UnsupportedSchemaKeyword",
    "Visibility",
    "WireSchemaViolation",
    "assert_supported_keywords",
    "check_contract_version",
    "compute_effective_scope",
    "declared_columns",
    "declared_tables",
    "hash_secret",
    "load_wire_schema",
    "make_queued_receipt",
    "parse_claim_status",
    "parse_version",
    "payload_hash",
    "reject_server_owned_fields",
    "validate_wire",
    "verify_secret",
    "wire_schema_names",
]
